version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  users-mongo:
    image: mongo
    ports:
       - "27017:27017"

  users-reading-service:
    image: statflo/vague-user-reading-service
    ports:
       - "8081:8081"
       
  users-writing-service:
    image: statflo/vague-user-writing-service
    ports:
       - "8080:8080"
    