logging:
  level:
    org.springframework.web: ERROR
    com.statflo.vague: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:

 kafka:
    bootstrap-servers: kafka:9092
 data:
   mongodb:
       host: users-mongo
       databaseName: vague-users 
   